version: '3.8'

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "8080:8080"
        restart: unless-stopped

    db:
        image: "mysql:8"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
              #            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: nfl
        ports:
            - "3306:3306"

    #frontend:
 
              #volumes:
              #    db_data: {}

